language: generic

before_install:
  - wget https://github.com/google/vroom/releases/download/v0.12.0/vroom_0.12.0-1_all.deb
  - sudo dpkg -i vroom_0.12.0-1_all.deb
  - eval "$(curl -Ss https://raw.githubusercontent.com/neovim/bot-ci/master/scripts/travis-setup.sh) nightly-x64"
  - sudo apt-get install -q python python3 python3-pip python-pip


install:
  - pip install -q neovim
  - pip3 install -q neovim

script: ./run_tests.sh

